[build]
builder = "nixpacks"
buildCommand = "cp prisma/schema.postgresql.prisma prisma/schema.prisma && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
